### ISSUE TITLE
3.1.1-0 goyave bug

### ISSUE THREAD

**Issue by Doxelix** [TeamWin/android_device_samsung_goyave#2]
When I flashed 3.1.1-0 Recovery... it's boot loop.

I have Samsung Galaxy Tab 3 Lite 7.0....

Android: 4.4.4

**Comment by ProjectT110** [comment]
Hello, what's the codename and model number of your device?

**Comment by Doxelix** [comment]
Model: SM-T113
Codename: I don't understand... :(

**Comment by ProjectT110** [comment]
Okay, it should be the correct device... Did you enable OEM Unlocking in the developer settings?

**Comment by Doxelix** [comment]
But... There is no OEM Unlocking on Samsung Tablet, I think. And no, I didn't enable OEM Unlocking.

**Comment by ProjectT110** [comment]
Um, you need to enable the setting to be able to run custom stuff.
Just enable OEM Unlocking from the setting and re-flash TWRP. :smiley:

**Comment by Doxelix** [comment]
Oh... but.. I have TWRP 3.0-2.0, but when I want to flash new version, it's just a bootloop.

**Comment by ProjectT110** [comment]
Oh... Welp, out of luck I guess... You could provide last_kmsg logs.

**Comment by Doxelix** [comment]
Sorry, but what do you mean? last_kmgs? where is that?

**Comment by Doxelix** [comment]
Ok, I am closing issue, because 3.7 was released amd fixed many problems. :)
